spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/project?useSSL=false&serverTimezone=GMT%2b8&characterEncoding=UTF-8
    username: root
    password: qmdx00
    driver-class-name: com.mysql.cj.jdbc.Driver